version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./backend/
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/static
      - media:/app/media/

  frontend:
    env_file: .env
    build: ./frontend/
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static

  gateway:
    restart: always
    build: ./nginx/
    env_file: .env
    depends_on:
      - backend
    ports:
      - 9000:80
    volumes:
      - static:/static
      - media:/app/media/